from tkinter import *

def click(event):
    text=event.widget.cget("text")
    if text== "=":
        if scvalue.get().isdigit():
            value=int(scvalue.get())
        else:
            try:
                value=eval(screen.get())
            except Exception as e:
                print(e)
                value="Error"
        scvalue.set(value)
        screen.update()
    elif text == "C":
        scvalue.set("")
        screen.update()
    else:
        scvalue.set(scvalue.get() + text)
        screen.update()

root=Tk()

root.geometry('1920x1080')
root.title("Calculator By Talha")
root.wm_iconbitmap("MyIcon.ico")
scvalue=StringVar()
scvalue.set("")
screen=Entry(root,textvar = scvalue,font ="lucida 40 bold")
screen.pack(fill=X,ipadx=10,pady=1,padx=10)
f=Frame(root,bg="grey")
b=Button(f,text="9",padx=28,pady=10,font="lucida 35 bold")
b.pack(side=LEFT,padx=18,pady=2)
b.bind("<Button-1>",click)
b=Button(f,text="8",padx=28,pady=10,font="lucida 35 bold")
b.pack(side=LEFT,padx=18,pady=2)
b.bind("<Button-1>",click)
b=Button(f,text="7",padx=28,pady=10,font="lucida 35 bold")
b.pack(side=LEFT,padx=18,pady=2)
b.bind("<Button-1>",click)
f.pack()
f=Frame(root,bg="grey")
b=Button(f,text="6",padx=28,pady=10,font="lucida 35 bold")
b.pack(side=LEFT,padx=18,pady=2)
b.bind("<Button-1>",click)
b=Button(f,text="5",padx=28,pady=10,font="lucida 35 bold")
b.pack(side=LEFT,padx=18,pady=2)
b.bind("<Button-1>",click)
b=Button(f,text="4",padx=28,pady=10,font="lucida 35 bold")
b.pack(side=LEFT,padx=18,pady=2)
b.bind("<Button-1>",click)
f.pack()
f=Frame(root,bg="grey")
b=Button(f,text="3",padx=28,pady=10,font="lucida 35 bold")
b.pack(side=LEFT,padx=18,pady=2)
b.bind("<Button-1>",click)
b=Button(f,text="2",padx=28,pady=10,font="lucida 35 bold")
b.pack(side=LEFT,padx=18,pady=2)
b.bind("<Button-1>",click)
b=Button(f,text="1",padx=28,pady=10,font="lucida 35 bold")
b.pack(side=LEFT,padx=18,pady=2)
b.bind("<Button-1>",click)
f.pack()
f=Frame(root,bg="grey")
b=Button(f,text="0",padx=31,pady=10,font="lucida 35 bold")
b.pack(side=LEFT,padx=18,pady=2)
b.bind("<Button-1>",click)
b=Button(f,text="-",padx=31,pady=10,font="lucida 35 bold")
b.pack(side=LEFT,padx=18,pady=2)
b.bind("<Button-1>",click)
b=Button(f,text="*",padx=31,pady=10,font="lucida 35 bold")
b.pack(side=LEFT,padx=18,pady=2)
b.bind("<Button-1>",click)
f.pack()
f=Frame(root,bg="grey")
b=Button(f,text="/",padx=37,pady=10,font="lucida 35 bold")
b.pack(side=LEFT,padx=18,pady=2)
b.bind("<Button-1>",click)
b=Button(f,text="+",padx=26,pady=10,font="lucida 35 bold")
b.pack(side=LEFT,padx=18,pady=2)
b.bind("<Button-1>",click)
b=Button(f,text="=",padx=27,pady=10,font="lucida 35 bold")
b.pack(side=LEFT,padx=18,pady=2)
b.bind("<Button-1>",click)
f.pack()
f=Frame(root,bg="grey")
b=Button(f,text="C",padx=25,pady=10,font="lucida 35 bold")
b.pack(side=LEFT,padx=18,pady=2)
b.bind("<Button-1>",click)
b=Button(f,text="%",padx=23,pady=10,font="lucida 35 bold")
b.pack(side=LEFT,padx=18,pady=2)
b.bind("<Button-1>",click)
b=Button(f,text=".",padx=30,pady=10,font="lucida 35 bold")
b.pack(side=LEFT,padx=18,pady=2)
b.bind("<Button-1>",click)
f.pack()
root.mainloop()
